# NumPy 排序数组

* 排序意味着将元素放入有序序列中。
* 有序序列是具有与元素相对应的顺序的任何序列，如数字或字母顺序，升序或降序。
* NumPy ndarray 对象有一个名为 sort() 的函数，该函数将对指定的数组进行排序。
* 如果对二维数组使用 sort() 方法，两个数组都会被排序：
* 注意：此方法返回数组的副本，保持原始数组不变。

In [3]:
# 对数组进行排序：
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

# 按字母顺序对数组进行排序：
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

# 对布尔数组进行排序：
arr = np.array([True, False, True])
print(np.sort(arr))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]


In [4]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
