# NumPy 随机数据分布与排列

### 随机分布
* 随机分布是一组遵循特定概率密度函数的随机数。
* 概率密度函数：描述连续概率的函数。即数组中所有值的概率。
* 我们可以使用 random 模块的 choice() 方法基于定义的概率生成随机数。
* choice() 方法允许我们为每个值指定概率。
* 概率是通过 0 到 1 之间的数字来设置的，其中 0 表示该值永远不会出现，1 表示该值总是会出现。
### 元素的随机排列
* 排列是指元素的布局。例如，[3, 2, 1] 是 [1, 2, 3] 的一个排列，反之亦然。
* NumPy 的 Random 模块为此提供了两个方法：shuffle() 和 permutation()。

In [1]:
"""
生成包含 100 个值的一维数组，其中每个值必须为 3、5、7 或 9。
值为 3 的概率设置为 0.1
值为 5 的概率设置为 0.3
值为 7 的概率设置为 0.6
值为 9 的概率设置为 0
"""
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

[7 7 7 7 7 7 3 7 7 7 7 7 7 7 7 7 7 5 5 3 5 5 7 7 7 7 3 7 5 5 7 5 3 5 3 5 7
 5 7 7 7 7 7 7 7 7 7 5 5 7 7 5 3 3 7 7 5 7 7 7 3 5 7 5 5 5 5 7 5 7 7 7 3 7
 3 7 7 7 5 5 5 7 7 7 7 5 7 7 7 3 7 7 7 3 7 7 7 7 7 7]


In [2]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[5 7 7 7 7]
 [3 7 5 7 5]
 [3 7 7 7 7]]


### 数组的洗牌
* 洗牌是指就地改变元素的排列。即，在数组本身中改变。
* 提示：shuffle() 方法会更改原始数组。

In [3]:
# 随机打乱以下数组的元素：
from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

[5 3 4 2 1]


### 生成数组的排列
* 提示：permutation() 方法返回重新排列的数组（并保持原始数组不变）。

In [4]:
# 生成以下数组元素的随机排列：
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))

[4 5 3 1 2]
