# NumPy 简单算术

### 加法
* add() 函数对两个数组的内容求和，并将结果返回到一个新数组中。

In [2]:
# 将 arr1 中的值加到 arr2 中的值上：
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


### 减法
* subtract() 函数从另一个数组的值中减去一个数组的值，并在新数组中返回结果。

In [3]:
# 从 arr1 中的值减去 arr2 中的值：
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


### 乘法
* multiply() 函数将一个数组中的值与另一个数组中的值相乘，并在新数组中返回结果。

In [4]:
# 将 arr1 中的值与 arr2 中的值相乘：
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


### 除法
* divide() 函数将一个数组的值除以另一个数组的值，并在新数组中返回结果。

In [5]:
# 将 arr1 中的值除以 arr2 中的值：
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


### 幂
* power() 函数将第一个数组的值提升到第二个数组值的幂，并在新数组中返回结果。

In [ ]:
# 将 arr1 中的值提升到 arr2 中值的幂：
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


### 平方根
* sqrt() 函数将数组中的值开方，并在新数组中返回结果。

In [ ]:
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,25,81])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 5. 9.]


### 指数


In [1]:
print(np.exp(1))

NameError: name 'np' is not defined

### 对数（Logs）
* NumPy 提供了函数来执行以 2、e 和 10 为底的对数运算。
* 我们还将探索如何通过创建自定义 ufunc 来获取任何基数的日志。
* 如果无法计算对数，所有对数函数都会将 -inf 或 inf 放入元素中。

In [ ]:
# 使用 log2() 函数执行以 2 为底的对数运算。
import numpy as np

arr = np.arange(1, 10)
print(np.log2(arr))

# 使用 log10() 函数执行以 10 为底的对数运算。
arr = np.arange(1, 10)
print(np.log10(arr))

# 使用 log() 函数执行以 e 为底的对数运算。
arr = np.arange(1, 10)
print(np.log(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


* 任何底数的对数
    * NumPy 没有提供任何函数来计算任何底数的对数，因此我们可以使用 frompyfunc() 函数以及带有两个输入参数和一个输出参数的内置函数 math.log()：

In [ ]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))

1.7005483074552052


### 余数
* mod() 和 remainder() 函数都返回第一个数组中对应于第二个数组中值的余数，并在新数组中返回结果。

In [ ]:
# 返回余数：
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


### 商和余数
* divmod() 函数同时返回商和余数。返回值为两个数组，第一个数组包含商，第二个数组包含余数。

In [9]:
# 返回商和余数：
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


### 绝对值
* absolute() 和 abs() 函数都执行相同的元素级绝对值操作，但我们应该使用 absolute() 以避免与 Python 的内建 math.abs() 混淆。

In [10]:
# 返回绝对值：
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]
