# NumPy 统计函数

### 求和（Summations）

In [3]:
import numpy as np
# 将 arr1 中的值与 arr2 中的值相加：
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

# 将 arr1 中的值与 arr2 中的值相加：
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2])
print(newarr)

# 轴上求和 如果指定 axis=1，NumPy 将对每个数组中的数字求和。
# 对以下数组执行第1轴上的求和：
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
newarr = np.sum([arr1, arr2], axis=1)
print(newarr)

[2 4 6]
12
[6 6]


### 累积和
* 累积和指的是数组元素的部分累加。例如，[1, 2, 3, 4] 的部分和将为 [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10]。
* 使用 cumsum() 函数执行部分求和。

In [ ]:
arr = np.array([1, 2, 3])
newarr = np.cumsum(arr)
print(newarr)

### 乘积（Products）
* 要查找数组中元素的乘积，请使用 prod() 函数。

In [ ]:
# 求该数组中元素的乘积：
arr = np.array([1, 2, 3, 4])
x = np.prod(arr)
print(x)

# 求两个数组中元素的乘积：
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod([arr1, arr2])
print(x)

# 轴上乘积 如果指定 axis=1，NumPy 将返回每个数组的乘积。
# 对以下数组执行第 1 轴上的求和：

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

### 累积乘积
* 累积乘积意味着部分地取乘积。例如，[1, 2, 3, 4] 的部分乘积为 [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]
* 使用 cumprod() 函数执行部分乘积。

In [ ]:
arr = np.array([5, 6, 7, 8])
newarr = np.cumprod(arr)
print(newarr)

### 差分（Differences）
* 离散差分意味着减去两个连续的元素。例如，对于 [1, 2, 3, 4]，离散差分为 [2-1, 3-2, 4-3] = [1, 1, 1]
* 要找到离散差分，请使用 diff() 函数。

In [ ]:
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

# 两次计算以下数组的离散差分：
arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr, n=2)
print(newarr)

### LCM（最小公倍数，Lowest Common Multiple）

In [ ]:
import numpy as np

num1 = 4
num2 = 6
x = np.lcm(num1, num2)
print(x)

##### 求数组中的 LCM
* 要查找数组中所有值的最小公倍数，可以使用 reduce() 方法。
* 提示：reduce() 方法将在每个元素上使用 ufunc（在本例中为 lcm() 函数），并将数组减少一维。


In [ ]:
# 求下列数组值的最小公倍数：
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)

# 求数组中所有值的最小公倍数（LCM），其中数组包含从 1 到 10 的所有整数：
arr = np.arange(1, 11)
x = np.lcm.reduce(arr)
print(x)

### GCD（最大公约数，Greatest Common Denominator）

In [ ]:
num1 = 6
num2 = 9
x = np.gcd(num1, num2)
print(x)

##### 求数组中的 GCD
* 要查找数组中所有值的最大公因数，可以使用 reduce() 方法。
* 注意：reduce() 方法将对每个元素使用 ufunc（在本例中为 gcd() 函数），并将数组减少一维。

In [ ]:
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)

### 平均值
* * 要计算数组中元素的平均值，请使用 mean() 函数。

In [6]:
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))

2.5


### 中位数
* 要计算数组中元素的中位数，请使用 median() 函数。
* 数据个数为奇数：排序后中间的数值
* 数据个数为偶数：中间的两个数的平均值

In [7]:
print(np.median([4,1,2]))
print(np.median([1,1,1,1,1,1,1,1,1,100]))

2.0
1.0


### 分位数
* 要计算数组中元素的任意分位数，请使用 median() 函数。

In [ ]:
print(np.median([1,2,3]))
print(np.median([1,2,3,4]))
np.random.seed(0)
arr = np.random.randint(0,100,4)
print(arr)

print(np.median(arr))
print(np.percentile(arr,80))

2.0
2.5
[44 47 64 67]
55.5
65.2


### 标准差、方差
* 要计算数组中元素的标准差、方差，请使用 std() 和 var() 函数。

In [8]:
arr1 = np.array([1,2,1,2,1,1,1,2])
arr2 = np.array([1,0,3,0,0,0,4,3])
print(np.mean(arr1))
print(np.mean(arr2))
print(np.var(arr1))
print(np.var(arr2))

1.375
1.375
0.234375
2.484375


### 最大值、最小值
* 要计算数组中元素的最大值、最小值，请使用 max() 和 min() 函数。

In [9]:
print(arr)
print(np.max(arr), np.argmax(arr))
print(np.min(arr), np.argmin(arr))

[1 2 3 4]
4 3
1 0
