# NumPy 三角函数

### 三角函数
* NumPy 提供了 ufuncs sin()、cos() 和 tan()，它们以弧度为单位获取值，并生成相应的 sin、cos 和 tan 值。

In [1]:
import numpy as np
x = np.sin(np.pi/2)
print(x)

# 求 arr 中所有值的正弦值：
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
x = np.sin(arr)
print(x)

1.0
[1.         0.8660254  0.70710678 0.58778525]


### 度数与弧度互化
* 默认情况下，所有三角函数都以弧度为参数，但我们可以在 NumPy 中将弧度转换为度数，反之亦然。

In [2]:
# 将以下数组 arr 中的所有值转换为弧度：
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

# 将以下数组 arr 中的所有值转换为角度：
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
x = np.rad2deg(arr)
print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]


### 求角度
* 根据正弦、余弦、正切值求角度。例如：sin、cos 和 tan 的反函数（arcsin、arccos、arctan）。
* NumPy 提供了 ufunc arcsin()、arccos() 和 arctan()，它们根据给定的相应 sin、cos 和 tan 值生成弧度值。

In [3]:
# 求 1.0 的角度：
x = np.arcsin(1.0)
print(x)

# 求数组中所有正弦值的角度：
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)

1.5707963267948966
[ 1.57079633 -1.57079633  0.10016742]


### 斜边
* 在 NumPy 中使用勾股定理查找斜边。
* NumPy 提供了 hypot() 函数，该函数采用底值和垂直值，并根据勾股定理产生斜边。

In [4]:
# 求当底边为 4，垂直边为 3 时的斜边长度：
base = 3
perp = 4
x = np.hypot(base, perp)
print(x)

5.0
