# NumPy 集合操作

### 在 NumPy 中创建集合
* 我们可以使用 NumPy 的 unique() 方法来从任何数组中找到唯一的元素。例如，创建一个集合数组，但请记住，集合数组应该只是一维数组。

In [1]:
# 将以下包含重复元素的数组转换为集合：
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


### 求并集
* 要找到两个数组的唯一值，请使用 union1d() 方法。

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)

[1 2 3 4 5 6]


### 求交集
* 要仅查找两个数组中都存在的值，请使用 intersect1d() 方法。

In [3]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

[3 4]


### 求差集
* 要仅找到第一个集合中不存在于第二个集合中的值，请使用 setdiff1d() 方法。
* 注意：setdiff1d() 方法采用可选参数 assume_unique，如果将其设置为 True，则可以加快计算。处理集合时应始终将其设置为 True。

In [4]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)
print(newarr)

[1 2]


### 求对称差集
* 要仅查找两个集合中都不存在的值，请使用 setxor1d() 方法。
* 注意：setxor1d() 方法采用可选参数 assume_unique，如果将其设置为 True，可以加快计算。处理集合时应始终将其设置为 True。

In [5]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)
print(newarr)

[1 2 5 6]
