# NumPy 数组重塑

* 重塑意味着改变数组的形状。

* 数组的形状是每个维度中元素的数量。

* 通过重塑，我们可以添加或删除维度，或更改每个维度中的元素数量。

### 从一维重塑为二维

In [ ]:
# 将以下包含 12 个元素的一维数组转换为二维数组。
# 最外面的维度将有 4 个数组，每个数组有 3 个元素：
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 从一维重塑为三维

In [ ]:
# 将以下包含 12 个元素的一维数组转换为 3 维数组。
# 最外面的维度将有 2 个数组，其中包含 3 个数组，每个数组有 2 个元素：
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### 我们可以重塑成任何形状吗？
* 是的，只要两个形状中重塑所需的元素相同即可。

* 我们可以将 8 个元素的 1D 数组重塑为 4 个元素的 2 行 2D 数组，但我们无法将其重塑为 3 个元素的 3 行 2D 数组，因为这需要 3x3 = 9 个元素。

In [3]:
# 尝试将具有 8 个元素的 1D 数组转换为每个维度具有 3 个元素的 2D 数组（会引发错误）：
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

### 返回副本还是视图？
* 返回原始数组，因此它是一个视图。

In [4]:
# 检查返回的数组是副本还是视图：
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


### 未知维度
* 你可以有一个“未知”的维度。
* 这意味着您不必在重塑方法中为其中一个维度指定准确的数字。
* 将 -1 作为值传递，NumPy 将为您计算此数字。
* 注意：我们不能将 -1 传递给多个维度。

In [5]:
# 将具有 8 个元素的 1D 数组转换为具有 2x2 元素的 3D 数组：
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 展平数组
* 展平数组意味着将多维数组转换为 1D 数组。
* 我们可以使用 reshape(-1) 来做到这一点。
* 注意：NumPy 中有很多用于更改数组形状的函数，如 flatten、ravel，以及用于重新排列元素的 rot90、flip、fliplr、flipud 等。这些属于 numpy 的中级到高级部分。

In [6]:
# 将数组转换为一维数组：
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]
